exec /usr/bin/dunst
exec "~/bin/get-news -s 5 whdh.com wcvb.com reuters.com"
exec "picom -b"
exec lxqt-policykit-agent
exec "~/dotfiles/sway/sway-randomize-bg"
exec waybar
exec swayidle -w timeout 600 'swaylock -fc 000000'
exec protonvpn-app
