input "type:keyboard" {
    xkb_options compose:menu,ctrl:nocaps,shift:both_capslock
    xkb_numlock enabled
}

# in milliseconds, i.e., this hides the cursor after 3 seconds
seat seat0 hide_cursor 3000

input "1739:52581:SYNA1202:00_06CB:CD65_Touchpad" {
    tap disabled
    natural_scroll enabled
    dwt enabled
}
