#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

# Check for GNU stow

command -v stow
stow_exists=$?

if [ $stow_exists -eq 1 ]; then
    echo "GNU stow not found in PATH. This script relies on that utility."
    echo "Please install it."
    exit 1
fi

# If we get here, we're good

########## Variables

dir=/home/$USER/dotfiles                    # dotfiles directory
olddir=/home/$USER/dotfiles_old             # old dotfiles backup directory
home=/home/$USER
i3dir=$home/.config/i3
i3sdir=$home/.config/i3status
rofidir=$home/.config/rofi
zathuradir=$home/.config/zathura

echo "Changing to $dir..."
# Doesn't matter where we are in the moment
pushd $dir
echo -e "...Done\n"

packs="i3 i3status rofi top vim zathura"
for pack in $packs; do
    cp -Rv $pack $olddir
done

# list of files/folders to symlink
stow -v --dotfiles -t $home top
stow -v --dotfiles -t $home vim
stow -v -t $rofidir rofi
stow -v -t $i3dir i3
stow -v -t $i3sdir i3status
stow -v -t $zathuradir zathura

echo -e "\nGoing back to previous dir..."
popd
echo "...Done"
