#!/bin/bash
############################
# .make.sh
# This script creates symlinks from the home directory to any desired dotfiles in ~/dotfiles
############################

# Check for GNU stow

command -v stow &> /dev/null
stow_exists=$?

if [ $stow_exists -eq 1 ]; then
    echo "GNU stow not found in PATH. This script relies on that utility."
    echo "Please install it."
    exit 1
fi

# If we get here, we're good

########## Variables

home=/home/$USER
configdir=$home/.config
dir=$home/dotfiles                    # dotfiles directory
olddir=$home/dotfiles_old             # old dotfiles backup directory
alacrittydir=$configdir/alacritty
darkmandir=$configdir/darkman
darkmanscriptsdir=/$home/.local/share
dunstdir=$configdir/dunst
emacsdir=$home/.emacs.d
i3dir=$configdir/i3
i3sdir=$configdir/i3status
picomdir=$configdir/picom
rofidir=$configdir/rofi
swaydir=$configdir/sway
waybardir=$configdir/waybar
ytdlpdir=$configdir/yt-dlp
zathuradir=$configdir/zathura

echo "Changing to $dir..."
# Doesn't matter where we are in the moment
pushd $dir
echo -e "...Done\n"

packs="alacritty darkman darkman_scripts dunst emacs i3 i3status picom rofi sway top vim waybar yt-dlp zathura"
for pack in $packs; do
    cp -Rv $pack $olddir
done

for dir in $alacrittydir $darkmandir $darkmanscriptsdir $emacsdir $i3dir $i3sdir $picomdir $rofidir $swaydir $waybardir $ytdlpdir $zathuradir; do
    if [[ ! -d $dir ]]; then
        mkdir -p $dir
    fi
done

# list of files/folders to symlink
stow -v --dotfiles -t $home top
stow -v --dotfiles -t $home vim
stow --verbose --target $alacrittydir alacritty
stow --verbose --target $darkmandir darkman
stow --verbose --target $darkmanscriptsdir darkman_scripts
stow --verbose --target $dunstdir dunst
stow --verbose --target $emacsdir emacs
stow -v -t $picomdir picom
stow -v -t $rofidir rofi
stow --verbose --target $swaydir sway
stow -v -t $i3dir i3
stow -v -t $i3sdir i3status
stow --verbose --target $waybardir waybar
stow --verbose --target $ytdlpdir yt-dlp
stow -v -t $zathuradir zathura

echo -e "\nGoing back to previous dir..."
popd
echo "...Done"
