#!/bin/bash

# Simple wrapper to adjust and show brightness in i3
# Usage:
#     adjust-brightness <action>
# Actions:
#     -d -- decrease brightness
#     -i -- increase brightness

notif_cmd="notify-send --hint=int:transient:1 -t 700"

usage () {
    echo "adjust-brightness <action>"
    echo "Actions:"
    echo "    -d -- decrease brightness"
    echo "    -i -- increase brightness"
}

send_brightness_notif () {
    brightness_level=$(brightnessctl | grep Current | cut -d' ' -f4 | tr -d [\(\)])
    $notif_cmd "brightness $brightness_level"
}

if [[ $# -ne 1 ]]; then
    echo "Missing action."
    usage
    exit 1
fi

action=$1
case "$action" in
    "-d")
        brightness_level=$(brightnessctl | grep Current | cut -d' ' -f4 | tr -d [\(\)%])
        if [[ $brightness_level -gt 10 ]]; then
            brightnessctl set 10%-
            send_brightness_notif
        else
            $notif_cmd "Minimum useful brightness reached"
        fi
        ;;
    "-i")
        brightness_level=$(brightnessctl | grep Current | cut -d' ' -f4 \
            | tr -d [\(\)%])
        if [[ $brightness_level -lt 100 ]]; then
            brightnessctl set +10%
            send_brightness_notif
        else
            $notif_cmd "Maximum brightness reached"
        fi
        ;;
    *)
        usage
        ;;
esac
