# sane window splitting; new pane starts in same directory as pane that was
# active when the keystroke registered
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
